# Generated by Django 4.1.5 on 2023-02-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectwithimagefield',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='objectwithimagefield',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='objectwithimagefield',
            name='upload_path',
        ),
        migrations.AlterField(
            model_name='objectwithimagefield',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/{}'),
        ),
    ]
