# Generated by Django 4.1.5 on 2023-02-16 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_objectwithimagefield_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cover'),
        ),
    ]
