# Generated by Django 4.1.5 on 2023-02-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_game_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='story_line',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
