# Generated by Django 4.1.5 on 2023-02-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_game_story_line_alter_game_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='story_line',
            field=models.CharField(blank=True, default=None, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.CharField(blank=True, default=None, max_length=1500, null=True),
        ),
    ]
