# Generated by Django 4.1.5 on 2023-02-16 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_game_story_line_alter_game_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagebase',
            old_name='image_id',
            new_name='filename',
        ),
    ]
