# Generated by Django 4.1.5 on 2023-02-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_image_id_imagebase_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagebase',
            name='filename',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
