# Generated by Django 4.1.7 on 2023-03-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_gamemode_slug_alter_genre_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
