# Generated by Django 4.1.5 on 2023-02-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(max_length=8)),
                ('rating', models.TextField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('url', models.URLField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('url', models.URLField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('url', models.URLField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.TextField(choices=[('MG', 'Main Game'), ('DLC', 'DLC Addon'), ('EXP', 'Expansion'), ('BD', 'Bundle'), ('SEXP', 'Standalone Expansion'), ('MOD', 'Mod'), ('EP', 'Episode'), ('S', 'Season'), ('RM', 'Remake'), ('RMA', 'Remaster'), ('EG', 'Expanded Game'), ('P', 'Port'), ('F', 'Fork'), ('PCK', 'Pack'), ('U', 'Update')], default='MG', max_length=4)),
                ('age_ratings', models.ManyToManyField(to='api_populators.agerating')),
                ('genres', models.ManyToManyField(to='api_populators.genres')),
                ('themes', models.ManyToManyField(to='api_populators.theme')),
            ],
        ),
    ]
