# Generated by Django 4.1.7 on 2023-03-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(max_length=8)),
                ('rating', models.TextField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('url', models.URLField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('url', models.URLField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('url', models.URLField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('category', models.TextField(choices=[('MainGame', 'Main Game'), ('DLC', 'DLC Addon'), ('Expansion', 'Expansion'), ('Bundle', 'Bundle'), ('StandaloneExpansion', 'Standalone Expansion'), ('Mod', 'Mod'), ('Episode', 'Episode'), ('Season', 'Season'), ('Remake', 'Remake'), ('Remaster', 'Remaster'), ('ExpandedGame', 'Expanded Game'), ('Port', 'Port'), ('Fork', 'Fork'), ('Pack', 'Pack'), ('Update', 'Update')], default='MainGame', max_length=50)),
                ('age_ratings', models.ManyToManyField(to='api_populators.agerating')),
                ('genres', models.ManyToManyField(to='api_populators.genres')),
                ('themes', models.ManyToManyField(to='api_populators.theme')),
            ],
        ),
    ]
