# Generated by Django 4.1.7 on 2023-03-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_populators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.TextField(choices=[('MainGame', 'Main Game'), ('DLC', 'DLC Addon'), ('Expansion', 'Expansion'), ('Bundle', 'Bundle'), ('StandaloneExpansion', 'Standalone Expansion'), ('Mod', 'Mod'), ('Episode', 'Episode'), ('Season', 'Season'), ('Remake', 'Remake'), ('Remaster', 'Remaster'), ('ExpandedGame', 'Expanded Game'), ('Port', 'Port'), ('Fork', 'Fork'), ('Pack', 'Pack'), ('Update', 'Update')], default='MainGame', max_length=50),
        ),
    ]
